// pch.h: 这是预编译标头文件。
// 下方列出的文件仅编译一次，提高了将来生成的生成性能。
// 这还将影响 IntelliSense 性能，包括代码完成和许多代码浏览功能。
// 但是，如果此处列出的文件中的任何一个在生成之间有更新，它们全部都将被重新编译。
// 请勿在此处添加要频繁更新的文件，这将使得性能优势无效。

#ifndef PCH_H
#define PCH_H

// 添加要在此处预编译的标头
#include <msclr/marshal_cppstd.h>
#include <iostream>
#include <Windows.h>
#include <thread>
#include <vector>
#include <list>
#include <forward_list>
#include <conio.h>
#include <string>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <chrono>
#include <mutex>
#include <condition_variable>
#include <cassert>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cctype>
#include <climits>
#include <cfloat>
#include <cstdint>
#include <cinttypes>
#include <cerrno>
#include <cfenv>
#include <cassert>
#include <csignal>
#include <cstdarg>
#include <cstddef>
#include <clocale>
#include <cctype>
#include <cwchar>
#include <cwctype>
#include <cuchar>
#include <limits>
#include <exception>
#include <stdexcept>
#include <type_traits>
#include <typeinfo>
#include <memory>
#include <new>
#include <utility>
#include <initializer_list>
#include <tuple>
#include <array>
#include <valarray>
#include <bitset>
#include <functional>
#include <algorithm>
#include <random>
#include <chrono>
#include <ratio>
#include <complex>
#include <cfenv>
#include <csetjmp>
#include <cstdalign>
#include <cstdarg>
#include <cstdbool>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctgmath>
#include <ctime>
#include <cuchar>
#include <cwchar>
#include <cwctype>
#include <deque>
#include <iomanip>
#include <ios>
#include <iosfwd>
#include <iostream>
#include <istream>
#include <ostream>
#include <sstream>
#include <streambuf>
#include <string>
#include <vector>
#include <list>
#include <forward_list>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <bitset>
#include <complex>
#include <valarray>
#include <mutex>
#include <condition_variable>
#include <thread>
#include <future>
#include <filesystem>
#include <cassert>
#include <cerrno>
#include <cfloat>
#include <ciso646>

#endif //PCH_H
